### PR TITLE
Fixed some things

### PR DESCRIPTION
**Pull request by YellowZaki**
Fixed:

- TimeSkipEventListener swapped with SleepSkipEventListener. Versions pre 1.15 were not handling  SleepSkipEventListener so the boss bar didn't dissapear, title didn't work, heal/hunger neither...
- Player#sendTitle() is available from 1.12, not 1.14.
- night-skipped and storm-skipped titles were not working if the clock counter was enabled, since it was shown before the clock counter title stopped, so it was then overwritten. I've added a 5 ticks delay to show the skipped titles after SleepSkipEventEvent.

### CODE REVIEW

**Review by mrgeneralq — COMMENTED** [review]
Can you elaborate a bit more on this?

**Comment by YellowZaki** [comment]
> * Can you elaborate more on the sendTitle and override clock title?
> * I never make a static getter for the Plugin, I would not use this unless you can convince me otherwise

When sleeping, the clock animation is sent. As soon as it finishes, SleepSkipEvent is called.
The problem is that if you send the skip night title ("Good morning...") as soon as SleepSkipEvent is called, the clock animation hasn't finished yet, so it overrides the skip night title. Therefore, skip night title was not shown. By delaying the title just 5 ticks, the skip night title can be seen.

I made the getter for the Plugin in order to register the Runnable.

**Review by mrgeneralq — APPROVED** [review]
Thank you for your contribution. I approve the changes. These fixes and enhancements will be deployed in V4.15.1.

**Comment by mrgeneralq** [comment]
@YellowZaki , please reach out to me on discord
MrGeneralQ#0001

**Pull request merged**
